name: internity
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=2.18.6 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    hooks_riverpod: ^2.1.3
    introduction_screen: ^3.1.4
    flutter_native_splash: ^2.2.16

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0
    flutter_launcher_icons: ^0.11.0

# Configuration for flutter
flutter:
    uses-material-design: true
    assets:
        - assets/

# configuration for launcher Icon
flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/logo.png"
    min_sdk_android: 21 # android min sdk min:16, default 21

    # Android
    adaptive_icon_background: "#ffffff"
    adaptive_icon_foreground: "assets/images/icon.png"

    # iOS
    remove_alpha_ios: true

# Configuration for splash screen
flutter_native_splash:
    background_image: "assets/images/splash_background.png"
    image: assets/images/splash_icon.png
    android_12:
        image: assets/images/splash_icon.png
        background_image: "assets/images/splash_background.png"
    fullscreen: true
