// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDRcQcTV1tW3EysfEZEVMusd1U1bm4Z4U',
    appId: '1:642297705953:web:990b20d28901dd8729cea0',
    messagingSenderId: '642297705953',
    projectId: 'internity-d2059',
    authDomain: 'internity-d2059.firebaseapp.com',
    storageBucket: 'internity-d2059.appspot.com',
    measurementId: 'G-ND9801X1PR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKEBciaKlXeayoMBCj16-_kRQkt7kiUFQ',
    appId: '1:642297705953:android:673f24c37cb46bdb29cea0',
    messagingSenderId: '642297705953',
    projectId: 'internity-d2059',
    storageBucket: 'internity-d2059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe6QBwwi2B-s60JDp0ggvRk6CrwBghUxU',
    appId: '1:642297705953:ios:e3fa2243455d71c629cea0',
    messagingSenderId: '642297705953',
    projectId: 'internity-d2059',
    storageBucket: 'internity-d2059.appspot.com',
    iosClientId: '642297705953-5gltn9nahlhrnsfdidb2tq89r6egdlkp.apps.googleusercontent.com',
    iosBundleId: 'com.example.internity',
  );
}
